### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by justin-eckenweber**
This one should fix the following error:

2022-09-23 [20:21:27.040] [Server thread/CRITICAL]: InvalidArgumentException: "Amplifier must be in range 0 - 255, got -2" (EXCEPTION) in "pmsrc/src/entity/effect/EffectInstance" at line 111
--- Stack trace ---
  #0 pmsrc/src/entity/effect/EffectInstance(44): pocketmine\entity\effect\EffectInstance->setAmplifier(int -2)
  #1 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/armor/ShieldedEnchant(41): pocketmine\entity\effect\EffectInstance->__construct(object pocketmine\entity\effect\Effect#112565, int 2147483647, int -2, false)
  #2 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/traits/ToggleTrait(38): DaPigGuy\PiggyCustomEnchants\enchants\armor\ShieldedEnchant->toggle(object pocketmine\player\Player#168705, object pocketmine\item\Armor#339263, object pocketmine\inventory\ArmorInventory#247753, int 1, int 1, false)
  #3 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/traits/ToggleTrait(88): DaPigGuy\PiggyCustomEnchants\enchants\ToggleableEnchantment->onToggle(object pocketmine\player\Player#168705, object pocketmine\item\Armor#339263, object pocketmine\inventory\ArmorInventory#247753, int 1, int 1, false)
  #4 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/EventListener(262): DaPigGuy\PiggyCustomEnchants\enchants\ToggleableEnchantment::attemptToggle(object pocketmine\player\Player#168705, object pocketmine\item\Armor#339263, object pocketmine\item\enchantment\EnchantmentInstance#312380, object pocketmine\inventory\ArmorInventory#247753, int 1, false)
  #5 pmsrc/src/event/RegisteredListener(60): DaPigGuy\PiggyCustomEnchants\EventListener->onQuit(object pocketmine\event\player\PlayerQuitEvent#175514)
  #6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent#175514)
  #7 pmsrc/src/player/Player(2100): pocketmine\event\Event->call()
  #8 pmsrc/src/network/mcpe/NetworkSession(576): pocketmine\player\Player->onPostDisconnect(string[17] client disconnect, null)
  #9 pmsrc/src/network/mcpe/NetworkSession(509): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #10 pmsrc/src/network/mcpe/NetworkSession(578): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#219421, string[17] client disconnect)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(141): pocketmine\network\mcpe\NetworkSession->onClientDisconnect(string[17] client disconnect)
  #12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(75): pocketmine\network\mcpe\raklib\RakLibInterface->onClientDisconnect(int 439, string[17] client disconnect)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#111043)
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #16 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1663957287.0515)
  #17 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #18 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[34] /home/clientservers/server-283952/, string[42] /home/clientservers/server-283952/plugins/)
  #19 pmsrc/src/PocketMine(328): pocketmine\server()
  #20 pmsrc(11): require(string[71] phar:///home/serversoftwares/PocketMine_1.19.21.phar/src/PocketMine.php)
--- End of exception information ---

### CODE REVIEW

**Comment by DaPigGuy** [comment]
This doesn't fix the root issue where stack is going below zero.

**Comment by JustinLLDV** [comment]
This PR only fixes some crashes for me. It is up to you what you do with it. I use so all virions are included.

**Comment by Aericio** [comment]
I will cherrypick some of these commits out. Thanks.

**Comment by Aericio** [comment]
Merged this change: https://github.com/DaPigGuy/PiggyCustomEnchants/commit/d985aad2f042c091a10b2bebcbb11a443e57c196

**Pull request closed without merging**
