### PR TITLE
Update CustomEnchants.php

### PR DESCRIPTION
**Pull request by Vale914**
Please make sure your pull request complies with these guidelines:
- * [ ] Use same formatting
- * [ ] Changes must have been tested on PMMP.
- * [ ] Unless it is a minor code modification, you must use an IDE.
- * [ ] Have a detailed title, like "Fix CustomEnchants::getName() must be..."

#### **Testing Environment**

- PHP: 
- PMMP:
- OS:

### CODE REVIEW

**Comment by Vale914** [comment]
Update CustomEnchants.php

**Comment by Vale914** [comment]
Update CustomEnchants.php

**Comment by Vale914** [comment]
Fix

**Comment by ComboLordC** [comment]
Can u give me the phar download now then

**Comment by DaPigGuy** [comment]
https://poggit.pmmp.io/r/31525/PiggyCustomEnchants_dev-230.phar

**Pull request closed without merging**
