### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by MrNinja008**
Please make sure your pull request complies with these guidelines:
- * [✓ ] Use same formatting
- * [ ✓] Changes must have been tested on PMMP.
- * [ ] Unless it is a minor code modification, you must use an IDE.
- * [✓ ] Have a detailed title.

#### **What does the PR change?**
Bump Protocol Version to latest

#### **Testing Environment**

- PHP: 7.3
- PMMP: 3.23.21
- OS: linux

### CODE REVIEW

**Comment by IcyEndymion004** [comment]
Hmmmm yes

**Comment by IcyEndymion004** [comment]
It works

**Comment by IcyEndymion004** [comment]
Sorry it took 5 minutes

**Comment by Aericio** [comment]
In the future, please refrain from bumping plugin version yourself.

**Pull request merged**
