### PR TITLE
Added /ce info <enchant>

### PR DESCRIPTION
**Pull request by PotatoeTrainYT**
Please make sure your pull request complies with these guidelines:
- * [x] Use same formatting
- * [x] Changes must have been tested on PMMP.
- * [x] ***PLEASE*** don't use the GitHub Web Editor
- * [x] Have a detailed title like "Fix CustomEnchants::getName() must be..."

#### **What does the PR change?**

Adds /ce info <enchant>

#### **Testing Environment**

- PHP: 
- PMMP:
- OS:

### CODE REVIEW

**Comment by QuiverlyRivalry** [comment]
shall i help on descriptions?

**Comment by PotatoeTrainYT** [comment]
no, pig said he will do rest

**Comment by QuiverlyRivalry** [comment]
lop /shrug

**Comment by QuiverlyRivalry** [comment]
i already made it, it was for my functions command btw

**Comment by DaPigGuy** [comment]
Taken over by a pig.

**Comment by DaPigGuy** [comment]
bb273cc9b8991cf67dd320bde1cc0134e051c32c

**Pull request closed without merging**
