### PR TITLE
api update for future api's

### PR DESCRIPTION
**Pull request by XoticRealmsOwnerandDev**

### CODE REVIEW

**Comment by PotatoeTrainYT** [comment]
I dont really see the point of this because there won't be no big update to PocketMine-MP any time soon

**Comment by QuiverlyRivalry** [comment]
yeah, and simply changing the api will not do anything, if a new api is out. eg some events will be renamed, and simply changing the api is pointless

**Comment by jrodr10** [comment]
I think it was a joke, also there is sevreral big updates to PMMP on the daily some are plugin breaking changes which require a bump in API. Though i still see this PR as useless as 3.0.0-ALPHA15 is not likely to be out for a good 30 days

**Comment by Aericio** [comment]
Backwards compatibility doesn't work nicely.

**Comment by Aericio** [comment]
I just realized, he put `3.0.0-FUCKPMMP` in api list lmao.

**Pull request closed without merging**
