### PR TITLE
Updated protocol version

### PR DESCRIPTION
**Pull request by DPG896**
Ppls need it. Merge it now

Please make sure your pull request complies with these guidelines:
- * [ ] Use same formatting
- * [x] Changes must have been tested on PMMP.
- * [ ] Unless it is a minor code modification, you must use an IDE.
- * [ ] Have a detailed title.

#### **Testing Environment**

- PHP: idk
- PMMP: 3.23.1
- OS: Android

### CODE REVIEW

**Comment by Aericio** [comment]
I need proof that the server starts up and the plugin runs properly.

**Comment by IcyEndymion004** [comment]
Give me five

**Comment by IcyEndymion004** [comment]
Naaa

**Comment by MrNinja008** [comment]
> Naaa

Stfu

**Comment by MrNinja008** [comment]
It works tested on my server hosted on wither

**Comment by IcyEndymion004** [comment]
wack cock

**Pull request closed without merging**
